<?php
include '_head.php';
?>

<?php
include 'menulateral.php';
?>

<div class="container">
    <div class="row">

    </div>
</div>

<section class="background-cortes">
    <div class="container">
            <div class="row">
            <div class="col-md-12 text-center ">
                <h1 class="tipo">Defumados <br> no pit smoker com lenha de laranjeira.</h1>
            </div>
        </div>

        <div class="boxx">
            <div class="row">
            


                <div class="col-md-12 text-center tudoo">
                    <h1 class="prato">Costelinha Barbecue</h1>
                    <h3 class="descricao">Acompanha mandioca cozida e farofa de bacon.</h3>
                    <h1 class="dinheiro"> R$99,90</h1>
                </div>

                <!-- <div class="col-md-6 text-center tudoo ">
                    <h1 class="prato "></h1>
                    <h3 class="descricao"></h3>
                    <h1 class="dinheiro"> </h1>
                </div> -->
            </div>  
        </div>  
        <?php
        include 'footer.php';
        ?>
    </div>  
            
</section>
</body>