<?php
include '_head.php';
?>

<?php
include 'menulateral.php';
?>

<div class="container">
    <div class="row">

    </div>
</div>

<section class="background-cortes">
    <div class="container">
            <div class="row">
            <div class="col-md-12 text-center ">
                <h1 class="tipo">Kids</h1>
            </div>
        </div>

        <div class="boxx">
            <div class="row">
            


                <div class="col-md-6 text-center tudoo">
                    <h1 class="prato">Filé KidS</h1>
                    <h3 class="descricao">Tiras de filé com arroz branco e batata frita.</h3>
                    <h1 class="dinheiro"> R$34,90</h1>
                </div>

                <div class="col-md-6 text-center tudoo ">
                    <h1 class="prato ">Pork Kids </h1>
                    <h3 class="descricao">Porco desfiado com arroz branco e batata frita.</h3>
                    <h1 class="dinheiro"> R$34,90</h1>
                </div>
            </div>  
        </div>
        <?php
        include 'footer.php';
        ?>  
    </div>  
            
</section>
</body>